export const catchAsyncErrors = (theFunction) =>{
    return (req,res,next)=>{}
}